#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: [Your Name]
# Course: Open Source Software

echo "=========================================="
echo "   OPEN SOURCE MANIFESTO GENERATOR"
echo "=========================================="
echo "Answer three questions to generate your philosophy."
echo

# Interactive input using 'read' [cite: 193-196]
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

# Capture the current date and set the output filename [cite: 197, 198]
DATE=$(date +'%d %B %Y')
USER_NAME=$(whoami)
OUTPUT="manifesto_${USER_NAME}.txt"

# Compose the paragraph and write to file [cite: 199, 200]
{
    echo "--- THE OPEN SOURCE MANIFESTO ---"
    echo "Generated by: $USER_NAME"
    echo "Date: $DATE"
    echo "---------------------------------"
    echo "I believe in a world where tools like $TOOL belong to everyone."
    echo "To me, the core of open source is $FREEDOM."
    echo "In the spirit of collaboration, I commit to building $BUILD"
    echo "and sharing it freely with the global community."
    echo "---------------------------------"
} > "$OUTPUT"

echo
echo "SUCCESS: Your manifesto has been saved to $OUTPUT"
echo "------------------------------------------"
# Display the content of the generated file [cite: 202]
cat "$OUTPUT"
